function  [beta,timeQP]=LassoGP(Kaux,yapp,lambda,Lassooption);


if isfield(Lassooption,'alphainit');
    alphainit=Lassooption.alphainit;

else
    alphainit=0;
end;
[beta,theta_debias_QP_BB_mono,obj_QP_BB_mono,...
    timeQP,debias_start,mses]= ...
    GPSR_BB(yapp,Kaux,lambda,...
    'Debias',0,...
    'Monotone',1,...
    'Initialization',alphainit,...
    'StopCriterion',5,...
    'ToleranceA',Lassooption.KKTcond,...
    'ToleranceD',0.00001,...
    'Verbose',0);
